// go run mkasm_darwin.go arm64
// Code generated by the command above; DO NOT EDIT.

//go:build go1.13
// +build go1.13

#include "textflag.h"

TEXT libc_opendir_trampoline<>(SB),NOSPLIT,$0-0
	JMP	libc_opendir(SB)

GLOBL	·libc_opendir_trampoline_addr(SB), RODATA, $8
DATA	·libc_opendir_trampoline_addr(SB)/8, $libc_opendir_trampoline<>(SB)
