name: Test fastwalk on macOS amd64
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: macos-13
    strategy:
      matrix:
        go: ['1.22', '1.23', '1.24']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go test ./...
      - name: Test Race
        run: go test -race ./...
